### ISSUE TITLE
Posición del Signature

### ISSUE THREAD

**Issue by sejosema** [thegreenter/xmldsig#10]
Buenas consulta como puedo cambiar la posición del Signature es decir si le paso mi xml siempre me pone al final del todo.
Pero quiero que me coloque después de otra etiqueta que esta aproximadamente a la mitad del xml.

**Comment by giansalex** [comment]
Hola @sejosema , esta librería esta adaptada para firma de XML correspondiente a comprobantes electrónicos, puedes utilizar el [paquete original](https://github.com/robrichards/xmlseclibs)

**Comment by sejosema** [comment]
Claro lo mio también es comprobante electrónico solo que tengo que enviar en la penúltima etiqueta, la ultima seria para el qr de la factura electrónica solo por eso consultaba.

**Comment by giansalex** [comment]
@sejosema  este es el método que retorna el nodo donde se colocará la firma.
https://github.com/thegreenter/xmldsig/blob/4df6694e11d2a59255ed05a7262e7beb50368cfc/src/Sunat/SignedXml.php#L262

**Comment by sejosema** [comment]
Genial retorna la primera etiqueta siempre veré como modificar para que coloque en donde quiero.

Muchas gracias
