### ISSUE TITLE
Warning: openssl_sign(): supplied key param cannot be coerced into a private key 

### ISSUE THREAD

**Issue by vinoles** [thegreenter/xmldsig#2]
Hola amigo estoy tratando de usar tu librería cifrando con un archivo de extension .p12

$fileXmlName = "/path/file/factura.xml";
        $docXmlExport = $rootNode->asXML($fileXmlName);
        $docXml = $rootNode->asXML();
        
        $certPath ="/path/file/key_example.p12"; 

        $signer = new SignedXml();
        $signer->setCertificateFromFile($certPath);

        $xmlSigned = $signer->signFromFile($fileXmlName);
        echo $xmlSigned;

al final me sale esta notificacion : 
Warning: openssl_sign(): supplied key param cannot be coerced into a private key 

Pdrias ayudarme o indicarme que estoy haciendo mal??

saludos

**Comment by giansalex** [comment]
En la guia indica que se requiere un archivo `.pem` , que contenta tanto la clave publica y privada

**Comment by vinoles** [comment]
Ok amigo muchas gracias ...
