### ISSUE TITLE
duplicacion en el node <ds:X509Certificate> cuando se firma 

### ISSUE THREAD

**Issue by werpoz** [thegreenter/xmldsig#6]
cuando se firma de la manera 
![image](https://user-images.githubusercontent.com/23005641/58582856-45992080-8218-11e9-9558-7aff67526938.png)
se muesta el <ds:X509Certificate> repetido en 3 veces 
![image](https://user-images.githubusercontent.com/23005641/58582784-2d290600-8218-11e9-8ebb-8027d421fa03.png)

**Comment by giansalex** [comment]
Hola @werpoz , tal vez sea el contenido de `demo.pem`, también podrías compartir ese archivo.

**Comment by werpoz** [comment]
Vale acabo de revisar el contenido del certificado `demo.pem` y efectivamente se repite 3 veces , gracias por responder tan rápido 
![image](https://user-images.githubusercontent.com/23005641/58586435-a62c5b80-8220-11e9-9eae-cd1bc365aac7.png)
