### ISSUE TITLE
Values for getValidFrom() and getExpiration() are switched

### ISSUE THREAD

**Issue by lurifuchs** [thegreenter/xmldsig#7]
Then functions getValidFrom() and getExpiration() in class x509Certificate.php seems to have returned values switched. getValidFrom() returns validTo_time_t and getExpiration() returns validFrom_time_t. 

getValueFrom() should return value for `validFrom_time_t`.

**Comment by giansalex** [comment]
Thanks @davidajnered, i go to fix it.

**Comment by lurifuchs** [comment]
Thank you for the quick fix! Can you release a new version on packagist as well? :)

**Comment by giansalex** [comment]
Yes, ready!

**Comment by lurifuchs** [comment]
Best support ever! Thank you :)
