### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jlaraf81** [thegreenter/xmldsig#9]
Buenas noches. Por favor me podria ayudar con este error. gracias.

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\vendor\greenter\xmldsig\src\Sunat\firm5.php on line 5

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\vendor\greenter\xmldsig\src\Sunat\firm5.php on line 5

**Comment by giansalex** [comment]
Hola @jlaraf81, al parecer estas agregando codigo dentro de la carpeta del paquete, deberías crear otra carpeta e instalar `greenter/xmldsig` y allí agregar `firm5.php`.

Deberia quedar asi
```
|
|- vendor/
|- composer.json
|- firm5.php
```
